export const REGISTRATION_CHANGE_EMAIL = 'REGISTRATION_CHANGE_EMAIL';
export const REGISTRATION_CHANGE_PASSWORD = 'REGISTRATION_CHANGE_PASSWORD';
export const REGISTRATION_CHANGE_REPEAT_PASSWORD = 'REGISTRATION_CHANGE_REPEAT_PASSWORD';
